export const ORDER_INGREDIENTS = "ORDER_INGREDIENTS";
export const CONSTRUCTOR_INGREDIENTS = "CONSTRUCTOR_INGREDIENTS";
export const CONSTRUCTOR_BUNS = "CONSTRUCTOR_BUNS";
export const REMOVE_ELEMENT = "REMOVE_ELEMENT";
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR";
export const CHANGE_THE_ORDER_CONSTRUCTOR_INGREDIENTS =
  "CHANGE_THE_ORDER_CONSTRUCTOR_INGREDIENTS";
