export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';
export const SUCCESS_GET_INGREDIENTS: 'SUCCESS_GET_INGREDIENTS' = 'SUCCESS_GET_INGREDIENTS';
export const ERROR_TEXT_GET_INGREDIENTS: 'ERROR_TEXT_GET_INGREDIENTS' = 'ERROR_TEXT_GET_INGREDIENTS';
