export const OPEN_SHOW_MODAL_ORDER_NUMBER: 'OPEN_SHOW_MODAL_ORDER_NUMBER' = 'OPEN_SHOW_MODAL_ORDER_NUMBER';
export const CLOSE_SHOW_MODAL_ORDER_NUMBER: 'CLOSE_SHOW_MODAL_ORDER_NUMBER' = 'CLOSE_SHOW_MODAL_ORDER_NUMBER';

