export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
export const SUCCESS_GET_ORDER_NUMBER = 'SUCCESS_GET_ORDER_NUMBER';
export const ERROR_GET_ORDER_NUMBER = 'ERROR_GET_ORDER_NUMBER';
export const ERROR_TEXT_GET_ORDER_NUMBER = 'ERROR_TEXT_GET_ORDER_NUMBER';
export const RESET_OLD_ORDER_DATA = 'RESET_OLD_ORDER_DATA';
