export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const ERROR_TEXT_GET_REGISTER_USER = 'ERROR_TEXT_GET_REGISTER_USER';
export const ERROR_GET_REGISTER_USER = 'ERROR_GET_REGISTER_USER';
