export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const ERROR_TEXT_GET_REGISTER_USER = 'ERROR_TEXT_GET_REGISTER_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const ERROR_TEXT_GET_LOGIN_USER = 'ERROR_TEXT_GET_LOGIN_USER';
export const RESET_ERROR = 'RESET_ERROR';
export const IS_LOADING = 'IS_LOADING';
export const USER_INFO_DATA_SUCCESS = 'USER_INFO_DATA_SUCCESS';
export const ERROR_TEXT_GET_USER_INFO = 'ERROR_TEXT_GET_USER_INFO';
