export const WS_ORDERS_HISTORY_OPEN: "WS_ORDERS_HISTORY_OPEN" =
  "WS_ORDERS_HISTORY_OPEN";
export const WS_ORDERS_HISTORY_ERROR: "WS_ORDERS_HISTORY_ERROR" =
  "WS_ORDERS_HISTORY_ERROR";
export const WS_ORDERS_HISTORY_CLOSE: "WS_ORDERS_HISTORY_CLOSE" =
  "WS_ORDERS_HISTORY_CLOSE";
export const WS_ORDERS_HISTORY_GET_MESSAGE: "WS_ORDERS_HISTORY_GET_MESSAGE" =
  "WS_ORDERS_HISTORY_GET_MESSAGE";
export const WS_ORDERS_HISTORY_SEND_MESSAGE: "WS_ORDERS_HISTORY_SEND_MESSAGE" =
  "WS_ORDERS_HISTORY_SEND_MESSAGE";

export const WS_USER_ORDERS_HISTORY_OPEN: "WS_USER_ORDERS_HISTORY_OPEN" =
  "WS_USER_ORDERS_HISTORY_OPEN";
export const WS_USER_ORDERS_HISTORY_ERROR: "WS_USER_ORDERS_HISTORY_ERROR" =
  "WS_USER_ORDERS_HISTORY_ERROR";
export const WS_USER_ORDERS_HISTORY_CLOSE: "WS_USER_ORDERS_HISTORY_CLOSE" =
  "WS_USER_ORDERS_HISTORY_CLOSE";
export const WS_USER_ORDERS_HISTORY_GET_MESSAGE: "WS_USER_ORDERS_HISTORY_GET_MESSAGE" =
  "WS_USER_ORDERS_HISTORY_GET_MESSAGE";
export const WS_USER_ORDERS_HISTORY_SEND_MESSAGE: "WS_USER_ORDERS_HISTORY_SEND_MESSAGE" =
  "WS_USER_ORDERS_HISTORY_SEND_MESSAGE";
